apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: goserver
  newName: maurosaito/gitopsfc
  newTag: 7f5ce66e19a5f0f7334f70bdc84886017ed07206
